packages:
  - '**'
  - '!**/test/**'
  - '!resolve-link-target/node_modules_link/**'

configDependencies:
  '@pnpm/plugin-better-defaults': 0.1.0+sha512-aWj7Jv9NcNs/OoazrxP6QspLgKRZ2PHj6wPris6ZCEqmXw+Z8zK59KLzl9NBFGRCO4PNA9pwDWLu+8N3NiqUAQ==

ignoredBuiltDependencies:
  - core-js

onlyBuiltDependencies:
  - '@pnpm/exe'
  - bun
  - yarn

overrides:
  '@types/node': 14.14.6
